<a href="https://colab.research.google.com/github/ahmedmamdouh111/Netflix-data-science-internship/blob/main/Netflix_Data_Science_Internship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Git & GitHub Setup

In [2]:
!git clone https://github.com/ahmedmamdouh111/Netflix-data-science-internship.git

Cloning into 'Netflix-data-science-internship'...
warning: You appear to have cloned an empty repository.

In [3]:
%cd /content/Netflix-data-science-internship

/content/Netflix-data-science-internship

In [4]:
!pwd

/content/Netflix-data-science-internship

In [5]:
!git config --global user.name "Ahmed Mamdouh"

In [6]:
!git config --global user.email "ahmed.do7a831@gmail.com"

# Task 1: Data Cleaning & Preprocessing

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
data=pd.read_csv("/content/Dataset.csv")

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [13]:
data.shape

(8790, 10)

In [10]:
data.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [14]:
data.duplicated().sum()

np.int64(0)

In [16]:
data['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [17]:
data['rating'].unique()

array(['PG-13', 'TV-MA', 'TV-PG', 'TV-14', 'TV-Y7', 'TV-Y', 'PG', 'TV-G',
       'R', 'G', 'NC-17', 'NR', 'TV-Y7-FV', 'UR'], dtype=object)

In [19]:
data['rating'].value_counts()

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [20]:
data['duration'].unique()

array(['90 min', '1 Season', '91 min', '125 min', '9 Seasons', '104 min',
       '87 min', '127 min', '76 min', '71 min', '131 min', '39 min',
       '36 min', '34 min', '35 min', '46 min', '67 min', '65 min',
       '61 min', '166 min', '103 min', '97 min', '106 min', '2 Seasons',
       '4 Seasons', '147 min', '94 min', '161 min', '111 min', '110 min',
       '105 min', '96 min', '124 min', '116 min', '98 min', '115 min',
       '122 min', '55 min', '99 min', '88 min', '100 min', '6 Seasons',
       '3 Seasons', '23 min', '102 min', '93 min', '95 min', '85 min',
       '83 min', '182 min', '5 Seasons', '92 min', '84 min', '48 min',
       '145 min', '119 min', '80 min', '128 min', '143 min', '273 min',
       '117 min', '114 min', '118 min', '108 min', '37 min', '121 min',
       '63 min', '142 min', '113 min', '154 min', '120 min', '82 min',
       '109 min', '101 min', '86 min', '77 min', '229 min', '15 min',
       '89 min', '156 min', '112 min', '107 min', '129 min', '44 min',
       '68 min', '135 min', '136 min', '165 min', '150 min', '133 min',
       '47 min', '70 min', '56 min', '58 min', '78 min', '140 min',
       '64 min', '59 min', '60 min', '69 min', '19 min', '22 min',
       '148 min', '189 min', '54 min', '141 min', '130 min', '81 min',
       '7 Seasons', '138 min', '132 min', '8 Seasons', '123 min',
       '66 min', '62 min', '74 min', '38 min', '13 min', '139 min',
       '126 min', '155 min', '159 min', '12 min', '137 min', '49 min',
       '72 min', '204 min', '25 min', '212 min', '73 min', '149 min',
       '224 min', '162 min', '75 min', '79 min', '32 min', '158 min',
       '164 min', '173 min', '181 min', '185 min', '21 min', '24 min',
       '51 min', '151 min', '42 min', '134 min', '177 min', '52 min',
       '53 min', '8 min', '57 min', '28 min', '50 min', '9 min', '26 min',
       '45 min', '171 min', '27 min', '33 min', '29 min', '146 min',
       '20 min', '157 min', '203 min', '41 min', '30 min', '17 min',
       '194 min', '15 Seasons', '233 min', '230 min', '237 min',
       '195 min', '253 min', '152 min', '190 min', '160 min', '208 min',
       '180 min', '144 min', '5 min', '174 min', '170 min', '192 min',
       '209 min', '187 min', '172 min', '16 min', '186 min', '11 min',
       '193 min', '176 min', '169 min', '40 min', '3 min', '168 min',
       '153 min', '214 min', '31 min', '163 min', '14 min', '179 min',
       '43 min', '200 min', '196 min', '167 min', '178 min', '228 min',
       '18 min', '205 min', '201 min', '191 min', '10 Seasons',
       '17 Seasons', '13 Seasons', '10 min', '312 min', '12 Seasons',
       '11 Seasons'], dtype=object)

In [22]:
data.groupby('type')['duration'].value_counts()

type     duration
Movie    90 min        152
         93 min        146
         94 min        146
         97 min        146
         91 min        144
                      ...
TV Show  12 Seasons      2
         13 Seasons      2
         15 Seasons      2
         11 Seasons      1
         17 Seasons      1
Name: count, Length: 220, dtype: int64

In [23]:
data['listed_in'].head(10)

0                                        Documentaries
1    Crime TV Shows, International TV Shows, TV Act...
2                   TV Dramas, TV Horror, TV Mysteries
3                   Children & Family Movies, Comedies
4     Dramas, Independent Movies, International Movies
5                         British TV Shows, Reality TV
6                                     Comedies, Dramas
7    Children & Family Movies, Comedies, Music & Mu...
8                         Dramas, International Movies
9           Children & Family Movies, Music & Musicals
Name: listed_in, dtype: object

In [24]:
data['country'].unique()

array(['United States', 'France', 'Brazil', 'United Kingdom', 'India',
       'Germany', 'Pakistan', 'Not Given', 'China', 'South Africa',
       'Japan', 'Nigeria', 'Spain', 'Philippines', 'Australia',
       'Argentina', 'Canada', 'Hong Kong', 'Italy', 'New Zealand',
       'Egypt', 'Colombia', 'Mexico', 'Belgium', 'Switzerland', 'Taiwan',
       'Bulgaria', 'Poland', 'South Korea', 'Saudi Arabia', 'Thailand',
       'Indonesia', 'Kuwait', 'Malaysia', 'Vietnam', 'Lebanon', 'Romania',
       'Syria', 'United Arab Emirates', 'Sweden', 'Mauritius', 'Austria',
       'Turkey', 'Czech Republic', 'Cameroon', 'Netherlands', 'Ireland',
       'Russia', 'Kenya', 'Chile', 'Uruguay', 'Bangladesh', 'Portugal',
       'Hungary', 'Norway', 'Singapore', 'Iceland', 'Serbia', 'Namibia',
       'Peru', 'Mozambique', 'Ghana', 'Zimbabwe', 'Israel', 'Finland',
       'Denmark', 'Paraguay', 'Cambodia', 'Georgia', 'Soviet Union',
       'Greece', 'West Germany', 'Iran', 'Venezuela', 'Slovenia',
       'Guatemala', 'Jamaica', 'Somalia', 'Croatia', 'Jordan',
       'Luxembourg', 'Senegal', 'Belarus', 'Puerto Rico', 'Cyprus',
       'Ukraine'], dtype=object)

In [26]:
data['country'].value_counts()

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

In [28]:
data['country']=data['country'].replace('Not Given','Unknown')

In [32]:
(data['country'] == 'Not Given').sum()

np.int64(0)

In [33]:
data['release_year'].describe()

count    8790.000000
mean     2014.183163
std         8.825466
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

In [40]:
data['date_added'].value_counts()

date_added
1/1/2020      110
11/1/2019      91
3/1/2018       75
12/31/2019     74
10/1/2018      71
             ...
12/2/2015       1
9/22/2016       1
9/17/2016       1
5/4/2017        1
9/20/2021       1
Name: count, Length: 1713, dtype: int64

In [42]:
data['date_added'] = pd.to_datetime(data['date_added'])

In [48]:
data['date_added'].dtype

dtype('<M8[ns]')

In [49]:
data['date_added'].describe()

count                             8790
mean     2019-05-17 21:44:01.638225408
min                2008-01-01 00:00:00
25%                2018-04-06 00:00:00
50%                2019-07-03 00:00:00
75%                2020-08-19 18:00:00
max                2021-09-25 00:00:00
Name: date_added, dtype: object

In [52]:
data['director'].unique()

array(['Kirsten Johnson', 'Julien Leclercq', 'Mike Flanagan', ...,
       'Majid Al Ansari', 'Peter Hewitt', 'Mozez Singh'], dtype=object)

In [53]:
data['director'].value_counts()

director
Not Given                 2588
Rajiv Chilaka               20
Alastair Fothergill         18
Raúl Campos, Jan Suter      18
Marcus Raboy                16
                          ...
Mark Risley                  1
Kirati Nakintanon            1
Christian De Vita            1
Abu Bakr Shawky              1
N. Chandra                   1
Name: count, Length: 4528, dtype: int64

In [54]:
data['director']=data['director'].replace('Not Given','Unknown')

In [55]:
data['show_id'].nunique()

8790

In [57]:
data['title'].value_counts()

title
9-Feb                                2
15-Aug                               2
22-Jul                               2
Septiembre, un llanto en silencio    1
Set Up                               1
                                    ..
Sei                                  1
Superlopez                           1
Oversize Cops                        1
Mirage                               1
The Highwaymen                       1
Name: count, Length: 8787, dtype: int64

In [58]:
data.loc[data['title']=='9-Feb']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
393,s3997,TV Show,9-Feb,Unknown,Pakistan,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Unknown,Pakistan,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

In [61]:
data.loc[data.duplicated(subset=data.columns.drop('show_id'),keep=False)]

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
393,s3997,TV Show,9-Feb,Unknown,Pakistan,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Unknown,Pakistan,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,2019-03-29,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,2018-10-10,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,2018-10-10,2018,R,144 min,"Dramas, Thrillers"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,2019-03-29,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"

In [62]:
data=data.drop_duplicates(subset=data.columns.drop('show_id'),keep='first')

In [63]:
data.duplicated(subset=data.columns.drop('show_id')).sum()

np.int64(0)

In [64]:
data.shape

(8787, 10)

In [65]:
data['title'].nunique()

8787

In [67]:
(data == 'Not Given').sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [68]:
print("Shape:", data.shape)
print("\nMissing values:")
print(data.isnull().sum())

print("\nDuplicate records:")
print(data.duplicated(subset=data.columns.drop('show_id')).sum())

print("\nData types:")
print(data.dtypes)

Shape: (8787, 10)

Missing values:
show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

Duplicate records:
0

Data types:
show_id                 object
type                    object
title                   object
director                object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
dtype: object

In [70]:
data.to_csv('netflix_cleaned.csv',index=False)

In [74]:
!git status

On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	netflix_cleaned.csv

nothing added to commit but untracked files present (use "git add" to track)

In [75]:
!git add netflix_cleaned.csv

In [78]:
!git commit -m "Add cleaned Netflix dataset"

[main (root-commit) cd6a568] Add cleaned Netflix dataset
 1 file changed, 8789 insertions(+)
 create mode 100644 netflix_cleaned.csv

In [84]:
from google.colab import userdata
import os

os.environ["GH_TOKEN"] = userdata.get("GITHUB_TOKEN")

In [85]:
!gh auth status

github.com
  ✓ Logged in to github.com account ahmedmamdouh111 (GH_TOKEN)
  - Active account: true
  - Git operations protocol: https
  - Token: github_pat_**********************************************************************************

In [86]:
!gh auth setup-git

In [87]:
!git push -u origin main

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 267.25 KiB | 5.04 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/ahmedmamdouh111/Netflix-data-science-internship.git
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.